repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-symlinks
      - id: check-illegal-windows-names
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/hadolint/hadolint
    rev: v2.14.0
    hooks:
      - id: hadolint
        name: Hadolint
        description: "Validate Dockerfile syntax and best practices"
        files: ^docker/.*/Dockerfile$
